SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE DocResponse(
	EmailWhatsapp VARCHAR(255) NOT NULL PRIMARY KEY,
	Status VARCHAR(10) NULL,
	Reason VARCHAR(1000) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;